---
name: module3_task3
on:
  push:
    branches: [main, master]
  schedule:
    - cron: 8 8 * * *
  pull_request:
    types: [opened, reopened, edited, ready_for_review]
    
jobs:
  module3_task3:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone and check out repository
        uses: actions/checkout@v3
      - name: Run setup script to install Hugo
        run: |
          cd module3_task3/
          ./setup.sh
        shell: bash
      - name: Build and store to create a package
        run: |
          cd module3_task3
          make package
      - name: Lint
        run: |
          cd module3_task3
          make lint
      - name: Integration-tests
        run: |
          cd module3_task3
          make build
          make validate
          make integration-tests
          make unit-tests
          make clean
      - name: Archive package
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: upload-package
          path: module3_task3/awesome-website.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v1.0.0')
        with:
          files: |
            module3_task3/awesome-website.zip
            module3_task3/DEPLOY.md
